### PR TITLE
Use the background image on every screen

### PR DESCRIPTION
**Pull request by PureTryOut**
~~This requires too much passing around of the background_image variable,
but good enough for now till the settings system has been reworked~~

**EDIT:** This depends on #139 and shouldn't be merged first.

### CODE REVIEW

**Comment by terrarier2111** [comment]
As far as i can see this would obscure the view on the world when in-game, you should handle the in-game scenario differently.

**Comment by PureTryOut** [comment]
I'm going to rebase this on #139, as it's relevant for how to retrieve the background image from the settings.

**Comment by PureTryOut** [comment]
@terrarier2111 fixed.

**Comment by terrarier2111** [comment]
Fixed by https://github.com/Lea-fish/Leafish/pull/198/commits/88ab33d19c42b63762bece4d90c3e3b92976a0b0

**Pull request closed without merging**
