### PR TITLE
Microsoft login

### PR DESCRIPTION
**Pull request by terrarier2111**
This is still WIP!

More testing is required, here are some instructions on how to do so (in the "UPDATE" section): https://github.com/Lea-fish/Leafish/issues/188#issue-1005061042

### CODE REVIEW

**Comment by skillman623** [comment]
It looks like we've been trying to handle O2Auth ourselves but there's already a rust package that handles this.
Is anyone opposed if I add it as a dependency?

**Comment by nametable** [comment]
So I tried this (putting in my own client_id and secret from Azure), and it seemed to login... but then when I click on the imported account I get a crash because the application tries to call `refresh` which is not implemented: https://github.com/Lea-fish/Leafish/blob/microsoft-login/protocol/src/protocol/microsoft2.rs#L48

**Comment by ChingChang9** [comment]
It fails to start with the following error:
```
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
```

**Comment by cooltexture1** [comment]
> It fails to start with the following error:
> 
> ```
> [wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
> ```

i think that error got fixed in #262 and #268 , this PR is pretty old so it is probably not included here

**Comment by slushie0** [comment]
Has there been any work on this since then? Afaict this has to get done in order for anyone to be able to use this project at all, so it seems a shame to let it gather dust.

**Comment by terrarier2111** [comment]
Superseded by https://github.com/Lea-fish/Leafish/pull/297 for now, we might consider reimplementing microsoft auth into the client itself at some point but then we should probably use https://github.com/azalea-rs/azalea/tree/main/azalea-auth/src

**Pull request closed without merging**
