### PR TITLE
quick fix for  #265

### PR DESCRIPTION
**Pull request by cooltexture1**
I have taken the code from https://github.com/iceiix/stevenarella/issues/714 which should be a quick fix for #265. I cant test it though as my computer runs wayland. So we should test if it works under X11, Windows and MacOs as iam not very sure.
In the long run we should probably update winit and or glutin to the newest versions as mentioned in  #266.

### CODE REVIEW

**Comment by terrarier2111** [comment]
> I have taken the code from [iceiix/stevenarella#714](https://github.com/iceiix/stevenarella/issues/714) which should be a quick fix for #265. I cant test it though as my computer runs wayland. So we should test if it works under X11, Windows and MacOs as iam not very sure. In the long run we should probably update winit and or glutin to the newest versions as mentioned in #266.

Could you mention the lack of testing in a FIXME and also explain the rationale behind this patch (+ add a link to #265 in said comment)

**Comment by cooltexture1** [comment]
> Could you mention the lack of testing in a FIXME and also explain the rationale behind this patch (+ add a link to #265 in said comment)
>
well i think the testing can be ignored now, according to the [winit documentation](https://docs.rs/winit/latest/winit/window/enum.CursorGrabMode.html) this should work on all platforms except mobile. 
I added a comment to explain the rationale and linked to the issue

**Comment by terrarier2111** [comment]
Okay, could you duplicate the comment for the other change in the code as well? After that this should be mergable

**Comment by cooltexture1** [comment]
Ok. It is done.

**Comment by terrarier2111** [comment]
Alright, nice thx

**Pull request merged**
