### PR TITLE
Fix buffer overrun in light data

### PR DESCRIPTION
**Pull request by nathanruiz**
We seem to be reading 4096 bytes rather than 2048 bytes per section in some cases. The array should always be 2048, 4 bits for each block in the chunk section (https://wiki.vg/index.php?title=Protocol&oldid=16317#Update_Light).

### CODE REVIEW

**Comment by terrarier2111** [comment]
Thank you for this work, did you test if your changes work?

**Comment by nathanruiz** [comment]
Yeah, I tested the changes with a 1.16.4 server

**Comment by terrarier2111** [comment]
Do you think you could fix the clippy warnings? Other than that this looks good!

**Comment by nathanruiz** [comment]
@terrarier2111 I've fixed the clippy warnings

**Comment by terrarier2111** [comment]
Thanks again

**Pull request merged**
